#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2022 10:12:30 AM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import unknown_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1042x563+435+140")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(0,  0)
        top.title("freefox password")
        top.configure(background="#282828")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        def save():
            variable = self.Entry1.get()+ "                                        " +  self.Entrysite.get()+ "                                               " + self.Entryusername.get()+ "                                                      " + self.Entrypassword.get()
            with open("password.txt", "a+") as file:
                file.write("\n")
                for password in variable:
                    file.write(password)
                file.close
                file.write("\n")
            self.Entry1.delete(0, END)
            self.Entrysite.delete(0, END)
            self.Entryusername.delete(0, END)
            self.Entrypassword.delete(0,END)

#=============================================================================================================

        def savepassword():
            self.frameajouter = tk.Frame(self.top)
            self.frameajouter.place(relx=-0.01, rely=-0.018, relheight=1.021
                                    , relwidth=1.022)
            self.frameajouter.configure(relief='groove')
            self.frameajouter.configure(borderwidth="2")
            self.frameajouter.configure(relief="groove")
            self.frameajouter.configure(background="#282828")
            self.frameajouter.configure(highlightbackground="#d9d9d9")
            self.frameajouter.configure(highlightcolor="black")

            self.Entrysite = tk.Entry(self.frameajouter)
            self.Entrysite.place(relx=0.16, rely=0.278, height=30, relwidth=0.229)
            self.Entrysite.configure(background="white")
            self.Entrysite.configure(disabledforeground="#a3a3a3")
            self.Entrysite.configure(font="TkFixedFont")
            self.Entrysite.configure(foreground="#000000")
            self.Entrysite.configure(highlightbackground="#d9d9d9")
            self.Entrysite.configure(highlightcolor="black")
            self.Entrysite.configure(insertbackground="black")
            self.Entrysite.configure(selectbackground="blue")
            self.Entrysite.configure(selectforeground="white")

            self.Label1 = tk.Label(self.frameajouter)
            self.Label1.place(relx=0.094, rely=0.278, height=31, width=34)
            self.Label1.configure(activebackground="#f9f9f9")
            self.Label1.configure(activeforeground="black")
            self.Label1.configure(anchor='w')
            self.Label1.configure(background="#282828")
            self.Label1.configure(compound='left')
            self.Label1.configure(disabledforeground="#a3a3a3")
            self.Label1.configure(font="-family {Segoe UI Black} -size 13 -weight bold")
            self.Label1.configure(foreground="#ffffff")
            self.Label1.configure(highlightbackground="#d9d9d9")
            self.Label1.configure(highlightcolor="black")
            self.Label1.configure(text='''site''')

            self.Entryusername = tk.Entry(self.frameajouter)
            self.Entryusername.place(relx=0.16, rely=0.383, height=30
                                     , relwidth=0.229)
            self.Entryusername.configure(background="white")
            self.Entryusername.configure(disabledforeground="#a3a3a3")
            self.Entryusername.configure(font="TkFixedFont")
            self.Entryusername.configure(foreground="#000000")
            self.Entryusername.configure(highlightbackground="#d9d9d9")
            self.Entryusername.configure(highlightcolor="black")
            self.Entryusername.configure(insertbackground="black")
            self.Entryusername.configure(selectbackground="blue")
            self.Entryusername.configure(selectforeground="white")

            self.Label2 = tk.Label(self.frameajouter)
            self.Label2.place(relx=0.019, rely=0.383, height=31, width=134)
            self.Label2.configure(activebackground="#f9f9f9")
            self.Label2.configure(activeforeground="black")
            self.Label2.configure(anchor='w')
            self.Label2.configure(background="#282828")
            self.Label2.configure(compound='left')
            self.Label2.configure(disabledforeground="#a3a3a3")
            self.Label2.configure(font="-family {Segoe UI Black} -size 12 -weight bold")
            self.Label2.configure(foreground="#ffffff")
            self.Label2.configure(highlightbackground="#d9d9d9")
            self.Label2.configure(highlightcolor="black")
            self.Label2.configure(text='''username/mail''')

            self.Entrypassword = tk.Entry(self.frameajouter)
            self.Entrypassword.place(relx=0.16, rely=0.487, height=30
                                     , relwidth=0.229)
            self.Entrypassword.configure(background="white")
            self.Entrypassword.configure(disabledforeground="#a3a3a3")
            self.Entrypassword.configure(font="TkFixedFont")
            self.Entrypassword.configure(foreground="#000000")
            self.Entrypassword.configure(highlightbackground="#d9d9d9")
            self.Entrypassword.configure(highlightcolor="black")
            self.Entrypassword.configure(insertbackground="black")
            self.Entrypassword.configure(selectbackground="blue")
            self.Entrypassword.configure(selectforeground="white")

            self.Label3 = tk.Label(self.frameajouter)
            self.Label3.place(relx=0.056, rely=0.487, height=31, width=84)
            self.Label3.configure(activebackground="#f9f9f9")
            self.Label3.configure(activeforeground="black")
            self.Label3.configure(anchor='w')
            self.Label3.configure(background="#282828")
            self.Label3.configure(compound='left')
            self.Label3.configure(disabledforeground="#a3a3a3")
            self.Label3.configure(font="-family {Segoe UI Black} -size 12 -weight bold")
            self.Label3.configure(foreground="#ffffff")
            self.Label3.configure(highlightbackground="#d9d9d9")
            self.Label3.configure(highlightcolor="black")
            self.Label3.configure(text='''password''')

            self.Buttonsave = tk.Button(self.frameajouter)
            self.Buttonsave.place(relx=0.16, rely=0.574, height=34, width=117)
            self.Buttonsave.configure(activebackground="#ececec")
            self.Buttonsave.configure(activeforeground="#000000")
            self.Buttonsave.configure(background="#d9d9d9")
            self.Buttonsave.configure(compound='left')
            self.Buttonsave.configure(disabledforeground="#a3a3a3")
            self.Buttonsave.configure(foreground="#000000")
            self.Buttonsave.configure(highlightbackground="#d9d9d9")
            self.Buttonsave.configure(highlightcolor="black")
            self.Buttonsave.configure(pady="0")
            self.Buttonsave.configure(text='''Save''',command=save)

            self.Button3 = tk.Button(self.frameajouter)
            self.Button3.place(relx=0.31, rely=0.574, height=34, width=97)
            self.Button3.configure(activebackground="#ececec")
            self.Button3.configure(activeforeground="#000000")
            self.Button3.configure(background="#d9d9d9")
            self.Button3.configure(compound='left')
            self.Button3.configure(disabledforeground="#a3a3a3")
            self.Button3.configure(foreground="#000000")
            self.Button3.configure(highlightbackground="#d9d9d9")
            self.Button3.configure(highlightcolor="black")
            self.Button3.configure(pady="0")
            self.Button3.configure(text='''back''',command=self.frameajouter.destroy)

            self.Label4 = tk.Label(self.frameajouter)
            self.Label4.place(relx=0.019, rely=0.017, height=21, width=224)
            self.Label4.configure(activebackground="#f9f9f9")
            self.Label4.configure(activeforeground="black")
            self.Label4.configure(anchor='w')
            self.Label4.configure(background="#282828")
            self.Label4.configure(compound='left')
            self.Label4.configure(disabledforeground="#a3a3a3")
            self.Label4.configure(font="-family {Segoe UI Black} -size 14 -weight bold")
            self.Label4.configure(foreground="#ffffff")
            self.Label4.configure(highlightbackground="#d9d9d9")
            self.Label4.configure(highlightcolor="black")
            self.Label4.configure(text='''version non securisé''')

            self.Label5 = tk.Label(self.frameajouter)
            self.Label5.place(relx=0.554, rely=0.226, height=81, width=304)
            self.Label5.configure(activebackground="#f9f9f9")
            self.Label5.configure(activeforeground="black")
            self.Label5.configure(anchor='w')
            self.Label5.configure(background="#282828")
            self.Label5.configure(compound='left')
            self.Label5.configure(disabledforeground="#a3a3a3")
            self.Label5.configure(font="-family {Segoe UI} -size 12 -weight bold")
            self.Label5.configure(foreground="#ffffff")
            self.Label5.configure(highlightbackground="#d9d9d9")
            self.Label5.configure(highlightcolor="black")
            self.Label5.configure(text='''ne perdee plus vos mots de passe !!!!''')

            self.Entry1 = tk.Entry(self.frameajouter)
            self.Entry1.place(relx=0.16, rely=0.174, height=30, relwidth=0.229)
            self.Entry1.configure(background="white")
            self.Entry1.configure(disabledforeground="#a3a3a3")
            self.Entry1.configure(font="TkFixedFont")
            self.Entry1.configure(foreground="#000000")
            self.Entry1.configure(highlightbackground="#d9d9d9")
            self.Entry1.configure(highlightcolor="black")
            self.Entry1.configure(insertbackground="black")
            self.Entry1.configure(selectbackground="blue")
            self.Entry1.configure(selectforeground="white")

            self.Label6 = tk.Label(self.frameajouter)
            self.Label6.place(relx=0.009, rely=0.174, height=31, width=144)
            self.Label6.configure(activebackground="#f9f9f9")
            self.Label6.configure(activeforeground="black")
            self.Label6.configure(anchor='w')
            self.Label6.configure(background="#282828")
            self.Label6.configure(compound='left')
            self.Label6.configure(disabledforeground="#a3a3a3")
            self.Label6.configure(font="-family {Segoe UI Black} -size 13 -weight bold")
            self.Label6.configure(foreground="#ffffff")
            self.Label6.configure(highlightbackground="#d9d9d9")
            self.Label6.configure(highlightcolor="black")
            self.Label6.configure(text='''application/site''')
#==================================================================================================================
        def viewpassword():
            self.Frameview = tk.Frame(self.top)
            self.Frameview.place(relx=-0.01, rely=-0.018, relheight=1.057
                                 , relwidth=1.012)
            self.Frameview.configure(relief='groove')
            self.Frameview.configure(borderwidth="2")
            self.Frameview.configure(relief="groove")
            self.Frameview.configure(background="#282828")
            self.Frameview.configure(highlightbackground="#d9d9d9")
            self.Frameview.configure(highlightcolor="black")

            self.Listbox1 = tk.Listbox(self.Frameview)
            self.Listbox1.place(relx=0.009, rely=0.387, relheight=0.592
                                , relwidth=0.99)
            self.Listbox1.configure(background="#111111")
            self.Listbox1.configure(disabledforeground="#a3a3a3")
            self.Listbox1.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
            self.Listbox1.configure(foreground="#ffffff")
            self.Listbox1.configure(highlightbackground="#d9d9d9")
            self.Listbox1.configure(highlightcolor="black")
            self.Listbox1.configure(selectbackground="blue")
            self.Listbox1.configure(selectforeground="white")

            with open("password.txt", "rb") as file:
                ligne = file.readline()
                while ligne:

                    ligne = file.readline()
                    self.Listbox1.insert(0, ligne)

            self.Button4 = tk.Button(self.Frameview)
            self.Button4.place(relx=0.019, rely=0.034, height=24, width=127)
            self.Button4.configure(activebackground="#ececec")
            self.Button4.configure(activeforeground="#000000")
            self.Button4.configure(background="#111111")
            self.Button4.configure(borderwidth="0")
            self.Button4.configure(compound='left')
            self.Button4.configure(disabledforeground="#a3a3a3")
            self.Button4.configure(foreground="#ffffff")
            self.Button4.configure(highlightbackground="#d9d9d9")
            self.Button4.configure(highlightcolor="black")
            self.Button4.configure(pady="0")
            self.Button4.configure(relief="flat")
            self.Button4.configure(text='''back''',command=self.Frameview.destroy)

            self.Label7 = tk.Label(self.Frameview)
            self.Label7.place(relx=0.019, rely=0.336, height=21, width=154)
            self.Label7.configure(activebackground="#f9f9f9")
            self.Label7.configure(activeforeground="black")
            self.Label7.configure(anchor='w')
            self.Label7.configure(background="#282828")
            self.Label7.configure(compound='left')
            self.Label7.configure(disabledforeground="#a3a3a3")
            self.Label7.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
            self.Label7.configure(foreground="#ffffff")
            self.Label7.configure(highlightbackground="#d9d9d9")
            self.Label7.configure(highlightcolor="black")
            self.Label7.configure(text='''application''')

            self.Label8 = tk.Label(self.Frameview)
            self.Label8.place(relx=0.227, rely=0.336, height=21, width=174)
            self.Label8.configure(activebackground="#f9f9f9")
            self.Label8.configure(activeforeground="black")
            self.Label8.configure(anchor='w')
            self.Label8.configure(background="#282828")
            self.Label8.configure(compound='left')
            self.Label8.configure(disabledforeground="#a3a3a3")
            self.Label8.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
            self.Label8.configure(foreground="#ffffff")
            self.Label8.configure(highlightbackground="#d9d9d9")
            self.Label8.configure(highlightcolor="black")
            self.Label8.configure(text='''site''')

            self.Label9 = tk.Label(self.Frameview)
            self.Label9.place(relx=0.436, rely=0.336, height=21, width=174)
            self.Label9.configure(activebackground="#f9f9f9")
            self.Label9.configure(activeforeground="black")
            self.Label9.configure(anchor='w')
            self.Label9.configure(background="#282828")
            self.Label9.configure(compound='left')
            self.Label9.configure(disabledforeground="#a3a3a3")
            self.Label9.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
            self.Label9.configure(foreground="#ffffff")
            self.Label9.configure(highlightbackground="#d9d9d9")
            self.Label9.configure(highlightcolor="black")
            self.Label9.configure(text='''username''')

            self.Label10 = tk.Label(self.Frameview)
            self.Label10.place(relx=0.664, rely=0.336, height=21, width=224)
            self.Label10.configure(activebackground="#f9f9f9")
            self.Label10.configure(activeforeground="black")
            self.Label10.configure(anchor='w')
            self.Label10.configure(background="#282828")
            self.Label10.configure(compound='left')
            self.Label10.configure(disabledforeground="#a3a3a3")
            self.Label10.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
            self.Label10.configure(foreground="#ffffff")
            self.Label10.configure(highlightbackground="#d9d9d9")
            self.Label10.configure(highlightcolor="black")
            self.Label10.configure(text='''password''')
#==================================================================================================================

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.345, rely=0.107, height=104, width=87)
        self.Button1.configure(activebackground="#282828")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#282828")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black",command=savepassword)
        photo_location = "./add.png"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Button1.configure(image=_img0)
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.tooltip_font = "TkDefaultFont"
        self.Button1_tooltip = \
        ToolTip(self.Button1, self.tooltip_font, '''ajouter un mots de passe''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.47, rely=0.124, height=84, width=87)
        self.Button2.configure(activebackground="#282828")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#282828")
        self.Button2.configure(borderwidth="0")
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black",command=viewpassword)
        photo_location = "./view.png"
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Button2.configure(image=_img1)
        self.Button2.configure(pady="0")
        self.Button2.configure(relief="flat")
        self.tooltip_font = "TkDefaultFont"
        self.Button2_tooltip = \
        ToolTip(self.Button2, self.tooltip_font, '''voir la liste des mots de passe''')

# Support code for Balloon Help (also called tooltips).
# derived from http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
from time import time, localtime, strftime
class ToolTip(tk.Toplevel):
    """ Provides a ToolTip widget for Tkinter. """
    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None,
                 delay=0.5, follow=True):
        self.wdgt = wdgt
        self.parent = self.wdgt.master
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        self.withdraw()
        self.overrideredirect(True)
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        tk.Message(self, textvariable=self.msgVar, bg='#FFFFDD',
                font=tooltip_font,
                aspect=1000).grid()
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')
    def spawn(self, event=None):
        self.visible = 1
        self.after(int(self.delay * 1000), self.show)
    def show(self):
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()
    def move(self, event):
        self.lastMotion = time()
        if self.follow is False:
            self.withdraw()
            self.visible = 1
        self.geometry('+%i+%i' % (event.x_root+20, event.y_root-10))
        try:
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)
    def hide(self, event=None):
        self.visible = 0
        self.withdraw()
    def update(self, msg):
        self.msgVar.set(msg)
#                   End of Class ToolTip

def start_up():
    unknown_support.main()

if __name__ == '__main__':
    unknown_support.main()




